### PR TITLE
Remove duplicate socket conenction. Don't update flash on Add paring for know UUID

### PR DESCRIPTION
**Pull request by maccoylton**
Added function to check for and remove old duplication sockets on new connection. 
Added code to not write flash if pairing updated for known UUUID

### CODE REVIEW

**Comment by nonameplum** [comment]
Did you find that this solve some issue?

**Comment by peros550** [comment]
Had the same question

**Comment by maccoylton** [comment]
Yes, I was seeing rapid memory consumption, the stale connections never got freed up and the device would crash. Haven’t got to the bottom of what causes the stale connections in the diet place 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mriksman** [comment]
This appears related to #141

**Comment by maccoylton** [comment]
May well be, I'm sure saw this issue on my led strip and rgbw light bulbs which use multipwm, although  I can;t categorically say I've never saw the issue on other types of accessories

**Pull request closed without merging**
