### PR TITLE
Added back-pointers for service->accessory and ch->service

### PR DESCRIPTION
**Pull request by mriksman**
Prior to commit fc46b99 on August 17 2020, the `homekit_accessories_init` function was in `accessories.c`, and it crucially linked `service->accessory` and `ch->service` at lines 433 and 443. Since that commit, this is no longer done, leaving these pointers NULL and breaking code that uses these back-pointers to navigate upwards, such as with this function `homekit_service_t *service = homekit_service_by_type(ch->service->accessory, HOMEKIT_SERVICE_ACCESSORY_INFORMATION);
`

### CODE REVIEW

**Comment by maximkulkin** [comment]
The reason why those back links were removed is to allow having all accessory definitions to be constant and thus not be placed into RAM, but instead loaded right from the flash. All changeable attributes (aid, iid, value, etc) were moved to accessory_/service_/characteristic_info.

I think support for back links can be added back, but is it worth really? You can always track those externally.

What kind of use case do you have?

**Comment by mriksman** [comment]
I could probably program it better, but I create my accessories/services dynamically using the `NEW_HOMEKIT` functions based on user supplied configuration.

I use the same callback function for both `LIGHTBULB` and `TELEVISION` (which are configured for different animations) services. This allows me to carefully manage the response which depends on what the current `TELEVISION->ACTIVE` is set to.
```
    *(s++) = NEW_HOMEKIT_SERVICE(LIGHTBULB, .primary=true, .characteristics=(homekit_characteristic_t*[]){
            NEW_HOMEKIT_CHARACTERISTIC(NAME, "LightbulbName"),
            NEW_HOMEKIT_CHARACTERISTIC(
                ON, false,
                .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(state_change_on_callback)
            ),
```
```
    *(s++) = NEW_HOMEKIT_SERVICE(TELEVISION, .characteristics=(homekit_characteristic_t*[]) {
        NEW_HOMEKIT_CHARACTERISTIC(
            ACTIVE, false,
                .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(state_change_on_callback)
        ),
```
In the callback, I then need to determine the current states of different characteristics to determine how to act. To do this, I need to go back to the parent accessory.
```
void state_change_on_callback(homekit_characteristic_t *_ch, homekit_value_t value, void *context) {
    homekit_service_t *light_service     = homekit_service_by_type(_ch->service->accessory, HOMEKIT_SERVICE_LIGHTBULB);
    homekit_service_t *tv_service        = homekit_service_by_type(_ch->service->accessory, HOMEKIT_SERVICE_TELEVISION);
    
    homekit_characteristic_t *active     = homekit_service_characteristic_by_type(tv_service, HOMEKIT_CHARACTERISTIC_ACTIVE);
    homekit_characteristic_t *active_id  = homekit_service_characteristic_by_type(tv_service, HOMEKIT_CHARACTERISTIC_ACTIVE_IDENTIFIER);

    homekit_characteristic_t *brightness = homekit_service_characteristic_by_type(light_service, HOMEKIT_CHARACTERISTIC_BRIGHTNESS);
    homekit_characteristic_t *hue        = homekit_service_characteristic_by_type(light_service, HOMEKIT_CHARACTERISTIC_HUE);
```
If I had just one accessory, I could simply save the accessory address during the accessory initialization to be used in `homekit_service_by_type`. But what if I had two accessories? How would I know who the parent is of the characteristic that initiated the callback?

In your modification on 17 August 2020, you removed this back-pointer initialization. However, the `struct _homekit_characteristic` has remained the same, and now `homekit_service_t *service` is left uninitialized with `NULL`. This modification only sets the variable correctly, and fixes the breaking code change that was made.

**Comment by maximkulkin** [comment]
Yes, I understand what you're trying to do and as I previously said there were reasons to remove updates to back links. I should have probably removed the back links altogether. My bad.

As an alternative solution I would recommend to use characteristic's "context" field. For example, you can create a structure that would store all characteristics of a particular accessory, and then you put pointer to that structure into every characteristic's context. Characteristic callbacks can just pull this structure from characteristic context and use it. That way you can even save time searching for characteristics.

```c

typedef struct {
    homekit_service_t *light_service;
    homekit_service_t *tv_service;
    
    homekit_characteristic_t *active;
    homekit_characteristic_t *active_id;

    homekit_characteristic_t *light_on;
    homekit_characteristic_t *brightness;
    homekit_characteristic_t *hue;
} MyAccessory;

MyAccessory* my_accessory = (MyAccessory*)malloc(sizeof(MyAccessory));

my_accessory->light_on = NEW_HOMEKIT_CHARACTERISTIC(
    ON, false,
    .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(state_change_on_callback),
    .context = my_accessory,
);

my_accessory->light_service = NEW_HOMEKIT_SERVICE(LIGHTBULB, .primary=true, .characteristics=(homekit_characteristic_t*[]){
  NEW_HOMEKIT_CHARACTERISTIC(NAME, "LightbulbName"),
  my_accessory->light_on,
  NULL
);
*(s++) = my_accessory->light_service;

void state_change_on_callback(homekit_characteristic_t *_ch, homekit_value_t value, void *context) {
  MyAccessory* my_accessory = (MyAccessory*)_ch->context;

  my_accessory->hue->value = ...;
}
```

Another possibility is to use callback context (in case callbacks is enough for you):
```c
my_accessory->light_on = NEW_HOMEKIT_CHARACTERISTIC(
    ON, false,
    .callback=HOMEKIT_CHARACTERISTIC_CALLBACK(state_change_on_callback, .context = my_accessory),
);

void state_change_on_callback(homekit_characteristic_t *_ch, homekit_value_t value, void *context) {
  MyAccessory* my_accessory = (MyAccessory*)context;
}
```

**Comment by mriksman** [comment]
Sorry for my ignorance, I am no programmer. I think I am starting to understand. This
``` c
const homekit_accessory_t *accessories[] = {
    HOMEKIT_ACCESSORY(.id=1, .category=homekit_accessory_category_lightbulb, .services=(homekit_service_t*[]){
        HOMEKIT_SERVICE(ACCESSORY_INFORMATION, .characteristics=(homekit_characteristic_t*[]){
            HOMEKIT_CHARACTERISTIC(NAME, "Sample LED"),
```
Would no longer work if this back-pointer was added back to `homekit_accessories_init`, because it is `const`?

**Comment by maximkulkin** [comment]
> Would no longer work if this back-pointer was added back to homekit_accessories_init, because it is const?

Correct. This is what I was trying to say.

**Comment by mriksman** [comment]
Understood. OK, I'll modify my program to track this differently. Thanks for looking at it!

**Pull request closed without merging**
