### PR TITLE
Update

### PR DESCRIPTION
**Pull request by AchimPieters**
Update the Font to Apple's San Francisco Font & QR-Code Redesign in illustrator and made  a higher resolution image.

### CODE REVIEW

**Comment by AchimPieters** [comment]
can't you see the files now?

**Comment by maximkulkin** [comment]
Yes, I do see them. One thing that I still need to check is license under which that font is provided by Apple and if they can be redistributed.

**Comment by AchimPieters** [comment]
@maximkulkin 

I downloaded the font from here: https://developer.apple.com/fonts/

I believe you may use the fonts, here's a discussion about it: https://discussions.apple.com/thread/7493969

**Comment by AchimPieters** [comment]
On the other hand:

[San Francisco Pro Font License.pdf](https://github.com/maximkulkin/esp-homekit/files/3419049/San.Francisco.Pro.Font.License.pdf)

Now I'm not sure anymore...

**Comment by maximkulkin** [comment]
Yes, the license is inside Apple's .dmg file the fonts are distributed in. And according to that it can not be redistributed. That's why originally I decided to go with more standard font and not try to get "the right font".

**Comment by AchimPieters** [comment]
I will try to fix that, You will here from me later on 👍

**Comment by AchimPieters** [comment]
I found the solution and fixed it San Francisco = Roboto ( Roboto = San Francisco) and its has been placed under [Apache License, Version 2.0](https://fonts.google.com/specimen/Roboto).

B2v_5TACAAAHdJ1

**Pull request merged**
