### PR TITLE
Pair setup issues due to mDNS fix

### PR DESCRIPTION
**Pull request by d4rkmen**
Another mDNS implementation for RTOS SDK and mDNS configuration logic changed

### CODE REVIEW

**Comment by maximkulkin** [comment]
What is the rationale behind sockets setup fix?

**Comment by maximkulkin** [comment]
Why do you need a new “discoverable” variable which is just an inverse of “paired” variable?

**Comment by d4rkmen** [comment]
Oops. Sockets issue is not related to pairing. It should be separate PR. The problem is: when controller closes the connection at session end (this is normal) accessory still tries to read data from connection (due to keepalive settings?)

**Comment by d4rkmen** [comment]
> Why do you need a new “discoverable” variable which is just an inverse of “paired” variable?

Otherwise it will call mdns config every request, not once

**Comment by maximkulkin** [comment]
> Oops. Sockets issue is not related to pairing. It should be separate PR. The problem is: when controller closes the connection at session end (this is normal) accessory still tries to read data from connection (due to keepalive settings?)

How do you know this is actually the case and you’re not making this up? How do you test? How do you know that this particular changes fix the problem?

**Comment by d4rkmen** [comment]
> How do you know this is actually the case and you’re not making this up? 

After I detected errors in logs (all the time) I have added some traces and found the error appers at the session end (phine closes connection). Then checked the HomeKitADK for socets setup as an instance.

>How do you test?

Tested on your samples

>How do you know that this particular changes fix the problem?

After 24h testing - there was no errors in the log. This particular issue is gone, but not sure is there new ones (so far) As we all can see, thing works for one not 100% works for all

**Pull request closed without merging**
